parameters:
#    jw_curso_sf2_backend.example.class: Jazzyweb\CursoSf2\BackendBundle\Example

services:
#    jw_curso_sf2_backend.example:
#        class: %jw_curso_sf2_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
