jw_curso_sf2_frontend:
    resource: "@JwCursoSf2FrontendBundle/Resources/config/routing.yml"
    prefix:   /

jw_curso_sf2_backend:
    resource: "@JwCursoSf2BackendBundle/Resources/config/routing.yml"
    prefix:   /

