parameters:
#    jw_curso_sf2_frontend.example.class: Jazzyweb\CursoSf2\FrontendBundle\Example

services:
#    jw_curso_sf2_frontend.example:
#        class: %jw_curso_sf2_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
